name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8", "11", "14"]
        clojure: ["1.11.1"]

    name: Java ${{ matrix.java }} Clojure ${{ matrix.clojure }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-lein-

    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test :unit

    - name: Check reflection warnings
      run:  '! lein check 2>&1 | egrep "Reflection warning|Performance warning"'
